### ISSUE TITLE
ETQ gestionnaire d'instance, utiliser l'infrastructure d'envoi des mails de mon organisation

### ISSUE THREAD

**Issue by dzc34** [demarches-simplifiees/demarches-simplifiees.fr#8028]
## Résumé

ETQ gestionnaire d'instance, utiliser l'infrastructure d'envoi des mails de mon organisation

## Cadre de cette contribution

> - L'ADULLACT est intéressé par cette évolution pour certaines instances DS des collectivités (_ARNia_, _Gironde Numérique,_ ...). 
> - Notre souhait est d'intégrer cette fonctionnalité sous forme de contribution au code source du logiciel DS. 
> - Nous avons mandaté le prestataire @synbioz pour développer cette fonctionnalité dans l'optique d'une contribution. 
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe `betagouv` sur ce ticket et sur les PRs (répondre aux commentaires, pousser des correctifs, ...).

[Ressource Adullact sur cette fonctionnalité](https://gitlab.adullact.net/demarches-simplifiees/evolution-du-logiciel-demarches-simplifiees/-/issues/46)

## Contexte

> Certains gestionnaires d'instance DS ont déjà en interne une infrastructure SMTP et ne souhaitent pas utiliser des services externes comme `Dolist`, `Mailjet` ou `Sendinblue` pour envoyer les mails applicatifs de DS.

Instances DS concernées par cette évolution : 
- _GIP ARNia_
- _Gironde Numérique_
- ...

## Actuellement

Les mails applicatifs de DS sont envoyés via les services externes `Dolist`, `Mailjet` ou `Sendinblue`.

## Comportement attendu

Le gestionnaire d'instance peut configurer un serveur SMTP ou Sendmail pour envoyer les mails applicatifs de DS, afin de pas utiliser les services externes `Dolist`, `Mailjet` ou `Sendinblue`.

## Ressources

Méthodes natives de Rails pour l'envoi des mails :
```ruby
config.action_mailer.delivery_method = :sendmail
config.action_mailer.delivery_method = :smtp 
```
Documentation  :
- https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
- https://guides.rubyonrails.org/configuring.html#configuring-action-mailer
  - https://guides.rubyonrails.org/configuring.html#config-action-mailer-smtp-settings
  - https://guides.rubyonrails.org/configuring.html#config-action-mailer-sendmail-settings
  - [configuration SMTP par défaut](https://github.com/mikel/mail/blob/master/lib/mail/network/delivery_methods/smtp.rb#L79)
  
  

### User stories

> Format : “En tant que” (ETQ), “je souhaite”, “afin de”

#### Serveur SMTP 
```
ETQ gestionnaire d'instance, 
Je souhaite, utiliser un serveur SMTP
             pour envoyer les mails applicatifs de DS 
             à la place des services externes d'envoi de mail Dolist, Mailjet et Sendinblue
Afin de pouvoir utiliser l'infrastructure d'envoi des mails de mon organisation 
     et ne pas utiliser les services externes d'envoi de mail Dolist, Mailjet et Sendinblue.
```

#### Serveur Sendmail sur la même machine que DS
```
ETQ gestionnaire d'instance, 
Je souhaite, utiliser un serveur Sendmail sur la même machine que l'application DS 
             pour envoyer les mails applicatifs de DS 
             à la place des services externes d'envoi de mail Dolist, Mailjet et Sendinblue
Afin de pouvoir utiliser l'infrastructure d'envoi des mails de mon organisation 
     et ne pas utiliser les services externes d'envoi de mail Dolist, Mailjet et Sendinblue.
```

#### Méthode native de Rails `sendmail` 

```ruby
# localhost sendmail
config.action_mailer.delivery_method = :sendmail
config.action_mailer.sendmail_settings = {
   location: '/usr/sbin/sendmail'
}
```

#### Méthode native de Rails `SMTP` 

> **TODO** : à compléter en fonction des réponses fournis par les différentes instances
>
> remarque :  certains exemples sont des configurations SMTP de Mailjet et Sendinblue pour permettre des tests rapides avec une configuration SMTP fonctionnelle. 

Exemple de code 
```ruby
config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = {
     user_name: ENV['SMTP_USERNAME'],
     password: ENV['SMTP_PASSWORD'],
     address: ENV['SMTP_HOST'],  # default: localhost
     port: ENV['SMTP_PORT'],     # default: 25
     domain: ENV['SMTP_HELO_DOMAIN'],
#    enable_starttls:      true, # default: false
#    enable_starttls_auto: true, # default: true
#    ssl:  true,
#    tls:  true,
     openssl_verify_mode: ENV['SMTP_OPENSSL_VERIFY_MODE'].presence || 'none', # 'none' or 'peer'
     authentication: ENV['SMTP_AUTHENTICATION_MECHANISMS'].presence || :plain # :cram_md5 | :login | :plain | :ntlm
}
```

Config 1 SMTP (25, without authentication, HELO domain)  ---> exemple générique
```yaml
SMTP Host:           smtp.app.example.org
SMTP Port:           25
SMTP User:           -  (without authentication)
SMTP Password:       -  (without authentication)
Authentication type: -  (without authentication)
STARTTLS enable:     false
SSL/TLS enable:      false
HELO domain:         diffusion.example.org
```

Config 2 SMTP (STARTTLS, 25, without authentication, HELO domain) ---> exemple générique
```yaml
SMTP Host:           smtp.app.example.org
SMTP Port:           25
SMTP User:           -  (without authentication)
SMTP Password:       -  (without authentication)
Authentication type: -  (without authentication)
STARTTLS enable:     true
SSL/TLS enable:      false
HELO domain:         diffusion.example.org
```

Config 3 SMTP (STARTTLS, 587, required authentication) ---> Exemple avec le SMTP Sendinblue
```yaml
SMTP Host:           smtp-relay.sendinblue.com
SMTP Port:           587
SMTP User:           xxxxxxxxx
SMTP Password:       xxxxxxxx
Authentication type: texte
STARTTLS enable:     true
SSL/TLS enable:      false
HELO domain:         ???
```

Config 4 SMTP (TLS, 465, required authentication) ---> Exemple avec les SMTP  Adullact, Mailjet ou Sendinblue 
```yaml
# SMTP Adullact
SMTP Host:           adullact-smtp.example.org
SMTP Port:           465
SMTP User:           xxxxxxxxx
SMTP Password:       xxxxxxxx
Authentication type: texte
STARTTLS enable:     false
SSL/TLS enable:      true
HELO domain:         ???

# SMTP Mailjet
SMTP Host:           in-v3.mailjet.com
SMTP Port:           465
SMTP User:           xxxxxxxxx
SMTP Password:       xxxxxxxx
Authentication type: texte
STARTTLS enable:     false
SSL/TLS enable:      true
HELO domain:         ???

# SMTP Sendinblue
SMTP Host:           smtp-relay.sendinblue.com
Port:                465
User:                xxxxxxxxx
Password:            xxxxxxxx
Authentication type: texte
STARTTLS enable:     false
SSL/TLS enable:      true
HELO domain:         ???
```

Config 5 SMTP (TLS, 465, required authentication, HELO domain) ---> exemple générique
```yaml
# SMTP 
SMTP Host:           smtp.example.org
SMTP Port:           465
SMTP User:           xxxxxxxxx
SMTP Password:       xxxxxxxx
Authentication type: texte
STARTTLS enable:     false
SSL/TLS enable:      true
HELO domain:         smtp-helo.example.org
```

Config 6 SMTP (25, required authentication de type **NTLM**, HELO domain) ---> exemple générique
```yaml
# SMTP (25, required authentication de type NTLM) 
SMTP Host:           smtp.example-intranet.local
SMTP Port:           25
SMTP User:           xxxxxxxxx
SMTP Password:       xxxxxxxx
Authentication type: ntlm
STARTTLS enable:     ???
SSL/TLS enable:      ???
HELO domain:         smtp.example-intranet.local
```

--------------------
> `trackingAdullactContrib`  `trackingAdullactARNiaContrib `
